use std::collections::HashMap;
use std::io;
use std::path::Path;
use std::time::Instant;
use log::{debug, info};
use thiserror::Error;
use crate::bytecode::{BytecodeSerialize, BytecodeStream};
use crate::compiler::BindingTable;
use crate::construct::ConstructExpansionErrorDetails;
use crate::parser::{ParseError, ParseErrorDetails};
use crate::semantic::{SemanticBindingDef, SemanticRepr, SemanticSymbol};

pub mod opcode;
pub mod value;
pub mod semantic;
pub mod parser;
mod util;
pub mod tokenizer;
pub mod compiler;
pub mod bytecode;
mod construct;

#[derive(Debug, Error)]
pub enum Error {
    #[error(transparent)]
    Io(#[from] io::Error),
    #[error("Tokenizer error at line {1}: {0}")]
    Tokenize(ParseError, usize),
    #[error("Parser error: {0}")]
    Parse(#[from] ParseErrorDetails),
    #[error("Compiler construct expansion error: {0}")]
    ConstructExpansion(ConstructExpansionErrorDetails),
    #[error("Compiler error: {0}")]
    Compile(#[from] compiler::CompilerError),
}
pub type CompileResult<T> = Result<T, Error>;

impl From<ConstructExpansionErrorDetails> for Error {
    fn from(details: ConstructExpansionErrorDetails) -> Self {
        Error::ConstructExpansion(details)
    }
}

/// Represents the input to the compiler, including the source code and module name.
#[derive(Debug, Default)]
pub struct CompilerInput {
    pub sources: HashMap<String, Vec<String>>,
    pub module_name: String,
}

/// Represents the output of the compiler, including the generated bytecode, symbols, and other debug information.
#[derive(Debug)]
pub struct CompilerOutput {
    pub bytes: BytecodeStream,
    pub semantic_lines: Vec<SemanticRepr>,
    pub semantic_lines_expanded: Vec<SemanticRepr>,
}

pub fn compile_source(input: CompilerInput) -> CompileResult<CompilerOutput> {
    let mut semantic_lines = HashMap::new();
    for (name, source) in input.sources.iter() {
        let processed = process_single_source(source)?;
        semantic_lines.insert(name.clone(), processed);
    }

    // binding table creation
    let binding_table = BindingTable::parse_and_lower(&mut semantic_lines)?;

    let mut bytecode_stream = BytecodeStream::new_with_header();
    // binding table
    binding_table.serialize(&mut bytecode_stream);

    Ok(CompilerOutput {
        bytes: bytecode_stream,
        semantic_lines: semantic_lines.into_iter().flat_map(|(_, v)| v).collect(),
        semantic_lines_expanded: Vec::new(),
    })
}

/// Processes a single source file into a sequence of semantic representations.
/// Steps Tokenization, parsing, and compiler construct expansion.
fn process_single_source(source: &[String]) -> CompileResult<Vec<SemanticRepr>> {
    let mut tokenized_lines = Vec::new();

    let sw = Instant::now();
    for (i, line) in source.iter().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        let res = match tokenizer::tokenize_line(line) {
            Ok(res ) => res,
            Err(e) => return Err(Error::Tokenize(e, i + 1)),
        };

        debug!("{res:?}");
        tokenized_lines.push(res);
    }

    let sw = Instant::now();
    let parsed = parser::parse_source(&tokenized_lines)?;

    // compiler construct expansion
    let sw = Instant::now();
    let parsed_expanded = construct::expand_construct_source(&parsed)?;

    Ok(parsed_expanded)
}