use std::time::Instant;
use log::{debug, info};
use thiserror::Error;
use crate::bytecode::BytecodeStream;
use crate::construct::ConstructExpansionErrorDetails;
use crate::parser::{ParseError, ParseErrorDetails};
use crate::semantic::SemanticRepr;

pub mod opcode;
pub mod value;
pub mod semantic;
pub mod parser;
mod util;
pub mod tokenizer;
pub mod compiler;
pub mod bytecode;
mod construct;

#[derive(Debug, Default)]
pub struct CompileOptions {

}

#[derive(Debug, Clone, Error)]
pub enum Error {
    #[error("Tokenizer error at line {1}: {0}")]
    Tokenize(ParseError, usize),
    #[error("Parser error: {0}")]
    Parse(#[from] ParseErrorDetails),
    #[error("Compiler construct expansion error: {0}")]
    ConstructExpansion(ConstructExpansionErrorDetails),
}

impl From<ConstructExpansionErrorDetails> for Error {
    fn from(details: ConstructExpansionErrorDetails) -> Self {
        Error::ConstructExpansion(details)
    }
}

/// Represents the output of the compiler, including the generated bytecode, symbols, and other debug information.
#[derive(Debug)]
pub struct CompilerOutput {
    pub bytes: BytecodeStream,
    pub semantic_lines: Vec<SemanticRepr>,
    pub semantic_lines_expanded: Vec<SemanticRepr>,
}

pub fn compile_source(source: &[&str], options: CompileOptions) -> Result<CompilerOutput, Error> {
    // Tokenize
    let mut tokenized_lines = Vec::new();
    debug!("Beginning tokenization step.");
    let sw = Instant::now();

    for (i, line) in source.iter().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        let res = match tokenizer::tokenize_line(line) {
            Ok(res ) => res,
            Err(e) => return Err(Error::Tokenize(e, i + 1)),
        };

        debug!("{res:?}");
        tokenized_lines.push(res);
    }

    info!("Tokenization completed in {:.3?} seconds.", sw.elapsed().as_secs_f64());

    // parse
    let sw = Instant::now();
    let parsed = parser::parse_source(&tokenized_lines)?;

    info!("Parsing completed in {:.3?} seconds.", sw.elapsed().as_secs_f64());

    // compiler construct expansion
    let sw = Instant::now();
    let parsed_expanded = construct::expand_construct_source(&parsed)?;
    info!("Compiler construct expansion completed in {:.3?} seconds.", sw.elapsed().as_secs_f64());

    // Semantic analysis and bytecode emission
    let mut output = BytecodeStream::new(parsed.len() * 16); // Estimate initial capacity
    output.write_u32(bytecode::F750_MAGIC);
    output.write_u32(bytecode::F750_VERSION);

    Ok(CompilerOutput {
        semantic_lines: parsed,
        semantic_lines_expanded: parsed_expanded,
        bytes: output,
    })
}